phases:

# Build all configurations for Windows
- template: /build/ci/phase-template.yml
  parameters:
    name: Windows
    buildScript: build.cmd
    buildMatrix:
      Py38:
        _configuration: RlsWinPy3.8
      Py37:
        _configuration: RlsWinPy3.7
      Py36:
        _configuration: RlsWinPy3.6
    buildQueue:
      name: Hosted VS2017
    testOptions: --includeExtendedTests

# Build all configurations for Mac
- template: /build/ci/phase-template.yml
  parameters:
    name: Mac
    buildScript: ./build.sh
    buildMatrix:
      Py38:
        _configuration: RlsMacPy3.8
      Py37:
        _configuration: RlsMacPy3.7
    buildQueue:
      name: Hosted macOS
    testOptions: --includeExtendedTests

# Build all configurations for Linux
  # Run build & tests on Ubuntu16 for Python3.8
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_Python38
    buildScript: ./build.sh
    testDistro: python38
    buildMatrix:
      Py38:
        _configuration: RlsLinPy3.8
    buildQueue:
      name: Hosted Ubuntu 1604
    testOptions: --includeExtendedTests

  # Run build & tests on Ubuntu16
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_Ubuntu16
    buildScript: ./build.sh
    testDistro: ubuntu16
    buildMatrix:
      Py37:
        _configuration: RlsLinPy3.7
      Py36:
        _configuration: RlsLinPy3.6
    buildQueue:
      name: Hosted Ubuntu 1604
    testOptions: --includeExtendedTests

  # Run build & tests on CentOS7
- template: /build/ci/phase-template.yml
  parameters:
    name: Linux_CentOS7
    buildScript: ./build.sh
    testDistro: centos7
    buildMatrix:
      Py37:
        _configuration: RlsLinPy3.7
    buildQueue:
      name: Hosted Ubuntu 1604
